import Head from 'next/head'
import Header from '../components/Header/Header'
import HomePage from '../components/Home/HomePage'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <>
      <Head>
        <title>Ken Ossai</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

     <Header />
     <div className="page">
      <HomePage />
     </div>
    </>
  )
}
