import Head from 'next/head'
// import HomePage from '../components/Home/HomePage'
import HomePage from './HomePage'

export default function Home() {
  return (
    <>
      <Head>
        <title>Ken Ossai</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

     <div className="page">
      <HomePage />
     </div>
    </>
  )
}
